version: '3.8'

services:
  app:
    container_name: vue-vite
    build:
      context: .
      dockerfile: ./docker/local/app.dockerfile
    ports:
      - "${DOCKER_APP_PORT}:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV
      - VITE_SERVER_URL_LOCAL
      - DOCKER_APP_PORT
      - PORT